case: Get k8s pod using tool
in:
  {
    "jsonrpc": "2.0",
    "method": "tools/call",
    "id": 2,
    "params":
      {
        "name": "get-k8s-resource",
        "arguments":
          {
            "context": "k3d-mcp-k8s-integration-test",
            "namespace": "test",
            "kind": "pod",
            "name": "nginx",
          },
      },
  }
out:
  {
    "jsonrpc": "2.0",
    "id": 2,
    "result":
      {
        "content":
          [
            {
              "type": "text",
              "text": !!ere '{"apiVersion":"v1","kind":"Pod","metadata":{/.*/"name":"nginx","namespace":"test"/.*/',
            },
          ],
        "isError": false,
      },
  }
