name: Cache goreleaser

# This workflow exists only to create cache for goreleaser binary
# so that it can be used in the release workflow, that runs on tags
# and cannot reuse caches from other runs except for the same tag or default branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on:  ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Cache installed binaries
        uses: actions/cache@v4
        with:
          path: /home/runner/go/bin
          key: ${{ runner.os }}-goreleaser

      - name: Install goreleaser
        run: |
          go install github.com/goreleaser/goreleaser/v2@latest
          which goreleaser
