# This is Github workflow that installs mcp-k8s from npm to various platforms and tests if it was installed

name: Install mcp-k8s

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install mcp-k8s
        run: |
          npm install -g @strowk/mcp-k8s

      - name: Test mcp-k8s
        run: |
          mcp-k8s version



