name: Release mcp-k8s to npm

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Install goreleaser
        run: |
          go install github.com/goreleaser/goreleaser/v2@latest

      - name: Run goreleaser build
        run: |
          goreleaser build --clean
          which goreleaser

      - name: Cache installed binary
        uses: actions/cache@v4
        with:
          path: /home/runner/go/bin
          key: ${{ runner.os }}-goreleaser

      - name: Publish to npm
        run: |
          chmod +x ./packages/publish_npm.sh
          ./packages/publish_npm.sh



