name: Release mcp-k8s to npm

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Cache installed binaries
        uses: actions/cache@v4
        with:
          path: /home/runner/go/bin
          key: ${{ runner.os }}-goreleaser

      - name: Install goreleaser
        run: |
          go install github.com/goreleaser/goreleaser/v2@latest
          which goreleaser

      - name: Run goreleaser build
        run: |
          goreleaser build --clean

      - name: Publish to npm
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          chmod +x ./packages/publish_npm.sh
          ./packages/publish_npm.sh

  install:
    strategy:
      matrix:
        os: 
          - windows-latest
          - ubuntu-latest
          - macos-latest
        arch: 
          - x64
          - arm64
    runs-on: ${{ matrix.os }}
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install mcp-k8s
        run: |
          npm install -g @strowk/mcp-k8s

      - name: Test mcp-k8s
        run: |
          mcp-k8s version



