name: test
run-name: Running tests
on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      # Install kubectl
      - run: 'curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"'
      # Install k3d
      - run: 'curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash'
      # Run tests
      - run: go test ./...